import { useState } from 'react';
import type { Language } from './direction-engine';
import './capability-showcase.css';
export type ShowcaseDirection = 'A' | 'B' | 'C';
const channels = [
  { name:'Organic search',sessions:'24,820',rate:'4.8%',revenue:'$18,640',delta:'+12.6%',values:[34,45,39,58,52,70,64,88,79,96],color:'#647e61' },
  { name:'Direct',sessions:'18,460',rate:'5.2%',revenue:'$16,280',delta:'+8.2%',values:[36,32,46,42,57,53,69,66,80,85],color:'#a5b691' },
  { name:'Paid social',sessions:'12,380',rate:'1.9%',revenue:'$7,420',delta:'−18.4%',values:[78,82,71,77,62,68,50,53,39,33],color:'#ce9178' },
];
function Spark({values,color}:{values:number[];color:string}) {return <svg viewBox="0 0 300 110" aria-hidden="true"><path d="M0 105H300M0 55H300M0 5H300" fill="none" stroke="#e8eae4"/><polyline points={values.map((n,i)=>`${i*300/(values.length-1)},${105-n}`).join(' ')} fill="none" stroke={color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/></svg>}
export function CapabilityShowcase({direction='A',language='zh'}:{direction?:ShowcaseDirection;language?:Language}) {
 const zh=language==='zh'; const [selected,setSelected]=useState(2); const row=channels[selected];
 const titles=zh?['先处理值得关注的变化。','把增长，放在一起比较。','每个判断，都有迹可循。']:['Know what needs your attention.','Put growth in perspective.','Follow the evidence.'];
 return <div className={`cap-app cap-${direction}`} data-showcase-direction={direction}>
 <aside className="cap-rail"><div className="cap-logo">◒ <strong>Forma</strong></div><span className="cap-workspace">STUDIO WORKSPACE ⌄</span><div className="cap-menu"><span>◫　{zh?'增长概览':'Overview'}</span><span>▥　{zh?'渠道表现':'Channels'}</span><span>◷　{zh?'活动记录':'Activity'}</span></div><div className="cap-team"><i>JL</i><span>Jamie Lee<small>Studio team</small></span></div></aside>
 <div className="cap-body"><div className="cap-topline"><span>Workspace / Growth overview</span><span>Oct 01 — Oct 07, 2026</span></div><header className="cap-heading"><div><p>YOUR WEEK, IN FOCUS</p><h2>{titles[['A','B','C'].indexOf(direction)]}</h2><span>{zh?'三个渠道，同一个增长目标。':'Three channels. One growth goal.'}</span></div><span className="cap-period">{zh?'本周概览':'Weekly report'}</span></header>
 <div className="cap-stats"><div><span>{zh?'总收入':'Revenue'}</span><strong>$42,340 <small>↗ 4.0%</small></strong><i>vs. previous week</i></div><div><span>{zh?'访问次数':'Sessions'}</span><strong>55,660 <small>↗ 9.2%</small></strong><i>across 3 channels</i></div><div><span>{zh?'需关注渠道':'Needs attention'}</span><strong>01 <small className="cap-negative">Paid social</small></strong><i>revenue −18.4%</i></div></div>
 {direction==='A'?<div className="cap-overview"><section className="cap-chart"><div className="cap-panel-title"><h3>{zh?'累计收入趋势':'Cumulative revenue'}</h3><span>01 — 07 OCT</span></div><div className="cap-chart-total">$42,340 <span>{zh?'本周收入':'this week'}</span></div><div className="cap-large-chart"><div className="cap-axis"><span>40k</span><span>20k</span><span>0</span></div><Spark values={[10,22,38,51,65,79,100]} color="#647e61"/></div><div className="cap-chart-dates"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></section><section className="cap-alert"><span>↘ {zh?'需要关注':'NEEDS ATTENTION'}</span><h3>Paid social</h3><strong>−18.4<small>%</small></strong><p>{zh?'收入低于上周，转化率为 1.9%。先检查这个渠道。':'Revenue is below last week. Conversion is 1.9%. Start your review here.'}</p><div><span>{zh?'当前收入':'Revenue'}</span><b>$7,420</b></div><small>{zh?'优先级 01 / 共 3 个渠道':'Priority 01 / 3 channels'}</small></section></div>:direction==='B'?<div className="cap-channel-cards">{channels.map(c=><section key={c.name}><i style={{background:c.color}}/><h3>{c.name}</h3><strong>{c.revenue}</strong><span className={c.delta.startsWith('−')?'cap-negative':'cap-positive'}>{c.delta} {zh?'较上周':'vs last week'}</span><Spark values={c.values} color={c.color}/><div><span>{zh?'转化率':'Conversion'}</span><b>{c.rate}</b></div><div><span>{zh?'访问次数':'Sessions'}</span><b>{c.sessions}</b></div></section>)}</div>:<div className="cap-evidence"><section><div className="cap-panel-title"><h3>{zh?'选择渠道，查看证据':'Select a channel to inspect'}</h3><span>3 RECORDS</span></div>{channels.map((c,i)=><button key={c.name} onClick={()=>setSelected(i)} aria-pressed={selected===i}><span style={{background:c.color}}/><div><strong>{c.name}</strong><small>{c.sessions} sessions · {c.rate} conversion</small></div><b>{c.revenue} ↗</b></button>)}</section><section className="cap-inspector"><span>RECORD / 0{selected+1}</span><h3>{row.name}</h3><dl><div><dt>{zh?'收入':'Revenue'}</dt><dd>{row.revenue}</dd></div><div><dt>{zh?'较上周':'vs last week'}</dt><dd>{row.delta}</dd></div><div><dt>{zh?'转化率':'Conversion'}</dt><dd>{row.rate}</dd></div></dl><p>{zh?'来源：示例渠道汇总表':'Source: sample channel summary'}</p><small>{zh?'统计区间与上方报表一致':'Same reporting period as overview'}</small></section></div>}
 <footer className="cap-bottom"><span>● {zh?'示例数据 · 用于比较设计取舍':'SAMPLE DATA · FOR DESIGN COMPARISON'}</span><span>FORMA / GROWTH INTELLIGENCE</span></footer></div></div>;
}
export function CapabilityStudies({language}:{language:Language}) {
 const zh=language==='zh';const [refined,setRefined]=useState(false);
 return <div className="cap-studies"><article><div className="cap-study-art"><div className="cap-stacked cap-stack-back" aria-hidden="true"><CapabilityShowcase direction="B" language={language}/></div><div className="cap-stacked cap-stack-front" aria-hidden="true"><CapabilityShowcase direction="A" language={language}/></div><span className="cap-art-tag">A / SIGNAL FIRST <span>B / COMPARE FIRST</span></span></div><small>01 / COMPARE</small><h3>{zh?'同一份数据，三种决策方式。':'One dataset. Three ways to decide.'}</h3><p>{zh?'把异常放大、把渠道并排，或把证据展开。布局改变的是用户先看什么、下一步做什么。':'Surface a signal, compare channels, or inspect the evidence. Layout changes what people see and do first.'}</p></article>
 <article><div className="cap-study-art"><div className="cap-edit-board"><div className="cap-edit-nav">◒ Forma <span>Overview / Growth</span></div><div className="cap-edit-region" data-refined={refined}><span>HERO ONLY ↖</span><h4>{refined?(zh?'付费社交转化下降，优先检查投放。':'Paid social is down. Review campaigns first.'):(zh?'先处理值得关注的变化。':'Know what needs your attention.')}</h4><p>{zh?'三个渠道，同一个增长目标。':'Three channels. One growth goal.'}</p></div><div className="cap-edit-kpis"><span>$42,340<small>REVENUE</small></span><span>55,660<small>SESSIONS</small></span><span>01<small>ATTENTION</small></span></div></div><span className="cap-art-tag">{zh?'字体、配色与其他区域保持不变':'TYPE, COLOR & OTHER REGIONS PRESERVED'}</span></div><small>02 / REFINE</small><h3>{zh?'只改标题，看见修改边界。':'A focused edit. A visible boundary.'}</h3><p>{zh?'试着让标题更具体。只有选中区域改变，下方数据与导航保持原样。':'Make the headline more specific. Only the selected region changes; metrics and navigation stay intact.'}</p><button className="cap-study-action" onClick={()=>setRefined(true)} disabled={refined}>{refined?(zh?'已应用示例修改':'Example edit applied'):(zh?'试改这个标题 ↗':'Try the headline edit ↗')}</button></article>
 <article><div className="cap-study-art"><div className="cap-history-card"><header><span>↶</span><div>VERSION HISTORY<small>{zh?'本页交互示例':'INTERACTIVE EXAMPLE'}</small></div></header><ol><li data-current={!refined}><i/><div><strong>v01 <span>{zh?'原始标题':'Original headline'}</span></strong><p>{zh?'先处理值得关注的变化。':'Know what needs your attention.'}</p></div><b>{!refined?'CURRENT':'SAVED'}</b></li><li data-current={refined}><i/><div><strong>v02 <span>{zh?'局部试改':'Scoped edit'}</span></strong><p>{refined?(zh?'已修改标题，其他区域不变':'Headline edited; other regions preserved'):(zh?'点击左侧按钮，试改标题':'Try the edit in the previous panel')}</p></div><b>{refined?'CURRENT':'—'}</b></li></ol><footer><span>1 REGION</span><span>0 TOKEN CHANGES</span></footer></div></div><small>03 / KEEP CONTROL</small><h3>{zh?'不满意，回到上一个版本。':'A way back, when you need it.'}</h3><p role="status">{refined?(zh?'v01 已保留。撤回会恢复原始标题，不会改变三版选择。':'v01 is preserved. Undo restores the original headline without selecting a direction.'):(zh?'当前为 v01。这里演示标题状态恢复；项目文件的快照由安装后的技能处理。':'Currently at v01. This demonstrates headline state restoration; the installed skill handles project snapshots.')}</p><button className="cap-study-action" onClick={()=>setRefined(false)} disabled={!refined}>{zh?'↶ 撤回示例修改':'↶ Undo example edit'}</button></article></div>;
}
