import { useEffect } from 'react';
import './expressive-directions.css';
export function ExpressiveDirections() {
 const params=new URLSearchParams(location.search);const id=params.get('direction')==='A'?'A':params.get('direction')==='C'?'C':'B';const zh=params.get('language')!=='en';
 useEffect(()=>{document.documentElement.lang=zh?'zh-CN':'en';document.title=`OFFSCRIPT — Direction ${id}`},[id,zh]);
 return <main className={`expressive expressive-${id}`} data-expressive-direction={id}>
 <nav><a href="/">offscript<span>®</span></a><div><a href="#work">{zh?'精选作品':'Selected work'}</a><a href="/#guided-demo">{zh?'探索三种风格':'Explore directions'} ↗</a></div><span>INDEPENDENT CREATIVE STUDIO</span></nav>
 {id==='A'?<section className="ex-hero ex-editorial"><div className="ex-editorial-copy"><p>ART DIRECTION & DIGITAL EXPERIENCES</p><h1>Less ordinary.<br/><em>More feeling.</em></h1><div className="ex-editorial-bottom"><span>01 — 03<br/>THE ART OF STANDING APART</span><p>{zh?'让品牌被感受，而不只是被看见。\n我们把独特的想法，做成值得停留的数字体验。':'Brands to feel, not just see.\nWe turn uncommon ideas into digital experiences worth staying for.'}</p></div><a className="ex-cta" href="/#guided-demo">{zh?'为我的品牌探索设计':'Find my design direction'} <span>↗</span></a></div><div className="ex-art editorial-art" aria-label={zh?'橘色雕塑与纸张的抽象构图':'Abstract orange sculpture on a paper background'}><div className="ex-orbit-label">OBJECT STUDY / Nº 001</div><div className="ex-sculpture"><i/><i/><i/><i/></div><span className="ex-art-caption">A different<br/><em>point of view.</em></span><span className="ex-art-index">(a)</span></div></section>:id==='B'?<section className="ex-hero ex-brutal"><div className="ex-brutal-top"><p>SMALL STUDIO.<br/>UNREASONABLY BIG IDEAS.</p><span>AVAILABLE FOR<br/>THE UNEXPECTED ↙</span></div><h1>GOOD IS<br/><span>NOT</span> ENOUGH<span className="ex-asterisk" aria-hidden="true">✳</span></h1><div className="ex-brutal-bottom"><p>{zh?'不做背景。成为焦点。\n为有态度的品牌，设计无法忽视的存在感。':'Don’t blend in. Become the reference.\nUnmissable identities for brands with something to say.'}</p><a className="ex-cta" href="/#guided-demo">{zh?'给我的项目一点大胆':'Make something bold'} ↗</a><span className="ex-sticker">100%<br/>OFF SCRIPT</span></div><div className="ex-ticker">STRATEGY ↗ IDENTITY ↗ DIGITAL ↗ CULTURE ↗ STRATEGY ↗ IDENTITY ↗</div></section>:<section className="ex-hero ex-digital"><div className="ex-digital-meta"><span>EXPERIMENT NO. 003</span><span>DESIGN AT THE EDGE OF POSSIBILITY</span></div><div className="ex-sphere" aria-hidden="true"><i/><i/><i/></div><div className="ex-digital-copy"><p>BEYOND THE EXPECTED</p><h1>Make room<br/>for <em>what’s next.</em></h1><p>{zh?'为下一种可能，创造新的界面。\n将大胆概念与精准交互，连接成完整体验。':'New interfaces for new possibilities.\nBold concepts. Precise interactions. One complete experience.'}</p><a className="ex-cta" href="/#guided-demo">{zh?'探索我的下一种可能':'Explore my next direction'} <span>↗</span></a></div><div className="ex-coordinates"><span>CREATIVE SYSTEMS / HUMAN FEELING</span><span>↘ SCROLL TO EXPLORE</span></div></section>}
 <section className="ex-work" id="work"><header><p>SELECTED DIRECTIONS / 2026</p><h2>{zh?'独特，是一种选择。':'Distinct by design.'}</h2><span>{zh?'概念作品 · 无客户背书':'CONCEPT STUDIES · NOT CLIENT WORK'}</span></header><div><article><span>01 / BRAND WORLD</span><h3>Outside the ordinary.</h3><p>{zh?'从品牌个性出发，让字体、色彩与构图说同一种语言。':'Type, color and composition built around a distinctive personality.'}</p></article><article><span>02 / DIGITAL EXPERIENCE</span><h3>Made to move you.</h3><p>{zh?'把视觉吸引力延伸到清晰的内容层级与行动路径。':'Visual character carried into clear content and a considered path to action.'}</p></article><article><span>03 / YOUR NEXT CHAPTER</span><h3>Make it yours.</h3><p>{zh?'在你的项目里生成、比较、局部打磨，再接入实际代码。':'Generate, compare, refine and integrate inside your own code project.'}</p><a href="/pricing">{zh?'了解方案与价格':'Explore plans & pricing'} ↗</a></article></div></section><footer className="ex-footer"><a href="/#guided-demo">← {zh?'返回设计比较':'Back to design comparison'}</a><span>OFFSCRIPT / {zh?'Variant Design 原创风格示例':'ORIGINAL VARIANT DESIGN STUDY'}</span></footer>
 </main>;
}
